### ISSUE TITLE
ELO Captains & Picking

### ISSUE THREAD

**Issue by LubricantJam** [DistrictNineHost/ModuleLIFT#13]
Dependent on their score on the website, picking the two highest ranking players as the captains and then not allowing them to pick the next two high ranking players until the end or something along those lines to ensure games are fair.

At the moment, the best players get picked first and make teams heavily unbalanced. People just play for easy wins and not for fun for both teams.

**Comment by WardPearce** [comment]
Okay, so I'm adding captain selection based on highest elo. But I don't see why blocking to next two highest elo players would help.
