### ISSUE TITLE
invalid match json

### ISSUE THREAD

**Issue by thboss** [DistrictNineHost/ModuleLIFT#26]
L 04/08/2019 - 13:37:15: [get5.smx] json_decode: character not identified as object or array at 0
L 04/08/2019 - 13:37:15: [get5.smx] Failed to load match config: invalid match json

**Comment by WardPearce** [comment]
What's your `sm_config_url ` cvar?

**Comment by thboss** [comment]
sm_config_url "62.210.142.245/sgc/6221014224527018.json"
gameserver amd website on same server
website url : http://62.210.142.245/sgc

**Comment by LubricantJam** [comment]
That's your issue. Use a domain and if you even browsed your own link you can see it's not set up. Says "box under maintenance" .
